// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvLEULKhHLs-j7GpfkWJoHcpa2KJSuo1s',
    appId: '1:786395538829:web:f93e5164deaac2ec20c9c4',
    messagingSenderId: '786395538829',
    projectId: 'crickyapp-f9706',
    authDomain: 'crickyapp-f9706.firebaseapp.com',
    storageBucket: 'crickyapp-f9706.appspot.com',
    measurementId: 'G-X3CNFN44EH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaFCkl1PlkozqTZYozRRtKaONldla8TQo',
    appId: '1:786395538829:android:4c88af85aa281fa820c9c4',
    messagingSenderId: '786395538829',
    projectId: 'crickyapp-f9706',
    storageBucket: 'crickyapp-f9706.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_FdixSZ-LzuCTL1XZGSCHXmFCV7z7Y-8',
    appId: '1:786395538829:ios:d2832fc5aa433ad020c9c4',
    messagingSenderId: '786395538829',
    projectId: 'crickyapp-f9706',
    storageBucket: 'crickyapp-f9706.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_FdixSZ-LzuCTL1XZGSCHXmFCV7z7Y-8',
    appId: '1:786395538829:ios:d2832fc5aa433ad020c9c4',
    messagingSenderId: '786395538829',
    projectId: 'crickyapp-f9706',
    storageBucket: 'crickyapp-f9706.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvLEULKhHLs-j7GpfkWJoHcpa2KJSuo1s',
    appId: '1:786395538829:web:c6a383ea37eec3cc20c9c4',
    messagingSenderId: '786395538829',
    projectId: 'crickyapp-f9706',
    authDomain: 'crickyapp-f9706.firebaseapp.com',
    storageBucket: 'crickyapp-f9706.appspot.com',
    measurementId: 'G-E6EM1B3N8F',
  );

}